version: '3.9'
services:
  win10:
    image: dockurr/windows:latest
    container_name: win10
    environment:
      - VERSION=10
      - PASSWORD=123456
      - RAM=8G
      - CPU=4
    ports:
      - "8006:8006"    # noVNC (yang kau tengah pakai sekarang)
      - "3389:3389"    # ‚Üê tambah baris ni kalau belum ada
      # ini untuk buka Windows dalam browser
    cap_add:
      - ALL
    privileged: true
    stop_grace_period: 3m
    restart: unless-stopped
