version: '3.9'
services:
  win10:
    image: dockurr/windows:latest
    container_name: win10
    environment:
      - VERSION=10
      - PASSWORD=123456
      - RAM=12G
      - CPU=6
    ports:
      - "8006:8006"
      # ini untuk buka Windows dalam browser
    cap_add:
      - ALL
    privileged: true
    stop_grace_period: 3m
    restart: unless-stopped
